import mongoose from 'mongoose';
import connectDB from '../src/lib/mongodb';
import Resource from '../src/models/Resource';

// Refold resources extracted from the document with fixed language values
const refoldResources = [
  // Stage 1A: Beginner Video Content
  {
    id: "comprehensible-korean-refold",
    slug: "comprehensible-korean-refold",
    title: "Comprehensible Korean",
    titleKorean: "Comprehensible Korean",
    description: "Simple comprehensible input based videos using whiteboard and marker, as well as some real clips. Amateur style but high quality content for beginners.",
    descriptionKorean: "화이트보드와 마커를 사용한 간단한 이해 가능한 입력 기반 비디오와 실제 클립. 초보자를 위한 고품질 콘텐츠.",
    image: "/images/resources/comprehensible-korean.svg",
    link: "https://www.youtube.com/c/ComprehensibleKorean",
    level: "Beginner",
    category: "Video",
    tags: [
      "comprehensible input",
      "youtube",
      "whiteboard",
      "beginner friendly",
    ],
    rating: 4.7,
    isFree: true,
    language: "Korean",
    features: [
      "Visual learning",
      "Beginner content",
      "Real clips",
      "Free access",
    ],
  },
  {
    id: "taewoong-comprehensible",
    slug: "taewoong-comprehensible",
    title: "Taewoong Korean Teacher - Comprehensible Input Korean",
    titleKorean: "Taewoong Korean Teacher - Comprehensible Input Korean",
    description: "Beginner series introducing basic Korean through powerpoint-style videos covering pop culture and daily life with visual aids and gestures.",
    descriptionKorean: "시각 자료와 제스처로 팝 문화와 일상 생활을 다루는 파워포인트 스타일 비디오를 통해 기본 한국어를 소개하는 초급 시리즈.",
    image: "/images/resources/taewoong.svg",
    link: "https://www.youtube.com/@taewoong_korean",
    level: "Beginner",
    category: "Video",
    tags: ["comprehensible input", "powerpoint", "pop culture", "gestures"],
    rating: 4.6,
    isFree: true,
    language: "Korean",
    features: [
      "Visual aids",
      "Pop culture topics",
      "Daily life content",
      "Gesture learning",
    ],
  },
  {
    id: "kiwi-korean-input",
    slug: "kiwi-korean-input",
    title: "KIWI - Korean Input with Images",
    titleKorean: "KIWI - Korean Input with Images",
    description: "Very easy beginner series with short, clear videos giving great examples for beginner-level grammar.",
    descriptionKorean: "초급 문법에 대한 훌륭한 예제를 제공하는 짧고 명확한 비디오가 있는 매우 쉬운 초급 시리즈.",
    image: "/images/resources/kiwi.svg",
    link: "https://www.youtube.com/@KIWI_korean",
    level: "Beginner",
    category: "Video",
    tags: ["grammar", "images", "short videos", "clear examples"],
    rating: 4.5,
    isFree: true,
    language: "Korean",
    features: [
      "Short videos",
      "Clear explanations",
      "Grammar examples",
      "Image-based learning",
    ],
  },
  {
    id: "immersion-korean-molip",
    slug: "immersion-korean-molip",
    title: "Molip Korean Immersion",
    titleKorean: "Molip Korean Immersion",
    description: "Very easy animated TPRS-style videos from super beginner level up to intermediate.",
    descriptionKorean: "초보자부터 중급까지 매우 쉬운 애니메이션 TPRS 스타일 비디오.",
    image: "/images/resources/immersion-korean.svg",
    link: "https://www.youtube.com/@ImmersionInKorean",
    level: "Beginner",
    category: "Video",
    tags: ["TPRS", "animated", "storytelling", "progressive difficulty"],
    rating: 4.6,
    isFree: true,
    language: "Korean",
    features: [
      "Animated content",
      "TPRS method",
      "Progressive levels",
      "Story-based",
    ],
  },
  {
    id: "storytime-korean",
    slug: "storytime-korean",
    title: "Storytime in Korean",
    titleKorean: "Storytime in Korean",
    description: "Beginner-level video game playthroughs, podcasts, and lightly animated TPRS-style videos.",
    descriptionKorean: "초급 수준의 비디오 게임 플레이스루, 팟캐스트 및 가벼운 애니메이션 TPRS 스타일 비디오.",
    image: "/images/resources/storytime.svg",
    link: "https://www.youtube.com/@storytimeinkorean",
    level: "Beginner",
    category: "Video",
    tags: ["gaming", "podcast", "TPRS", "animated"],
    rating: 4.5,
    isFree: true,
    language: "Korean",
    features: [
      "Game playthroughs",
      "Podcast episodes",
      "TPRS stories",
      "Varied content",
    ],
  },
  {
    id: "learn-korean-in-korean-channel",
    slug: "learn-korean-in-korean-channel",
    title: "Learn Korean in Korean",
    titleKorean: "Learn Korean in Korean",
    description: "Many videos that are listening practice as well as introductions to Korean grammar.",
    descriptionKorean: "듣기 연습과 한국어 문법 소개가 포함된 많은 비디오.",
    image: "/images/resources/learn-korean-in-korean.svg",
    link: "https://www.youtube.com/@LearnKoreaninKorean",
    level: "Beginner",
    category: "Video",
    tags: ["grammar", "listening", "korean only", "practice"],
    rating: 4.4,
    isFree: true,
    language: "Korean",
    features: [
      "Listening practice",
      "Grammar lessons",
      "Korean-only content",
      "Free lessons",
    ],
  },
  {
    id: "intuit-korean",
    slug: "intuit-korean",
    title: "Intuit Korean",
    titleKorean: "Intuit Korean",
    description: "Comprehensible input channel that slowly reads stories in Korean to help learners understand naturally.",
    descriptionKorean: "학습자가 자연스럽게 이해할 수 있도록 한국어로 천천히 이야기를 읽어주는 이해 가능한 입력 채널.",
    image: "/images/resources/intuit-korean.svg",
    link: "https://www.youtube.com/@IntuitKorean",
    level: "Beginner",
    category: "Video",
    tags: [
      "comprehensible input",
      "storytelling",
      "slow reading",
      "natural learning",
    ],
    rating: 4.5,
    isFree: true,
    language: "Korean",
    features: [
      "Slow reading",
      "Story focus",
      "Comprehensible input",
      "Natural learning",
    ],
  },
  {
    id: "learn-real-korean",
    slug: "learn-real-korean",
    title: "Learn Real Korean",
    titleKorean: "Learn Real Korean",
    description: "YouTube channel based on comprehensible input concepts for learning real Korean.",
    descriptionKorean: "실제 한국어를 배우기 위한 이해 가능한 입력 개념을 기반으로 한 YouTube 채널.",
    image: "/images/resources/learn-real-korean.svg",
    link: "https://www.youtube.com/@LearnRealKorean",
    level: "Beginner",
    category: "Video",
    tags: ["comprehensible input", "real korean", "authentic", "youtube"],
    rating: 4.4,
    isFree: true,
    language: "Korean",
    features: [
      "Real Korean",
      "Comprehensible input",
      "Authentic content",
      "Free videos",
    ],
  },
  // Stage 1A: Audio Content
  {
    id: "iyagi-ttmik-podcast",
    slug: "iyagi-ttmik-podcast",
    title: "Iyagi - TTMIK Podcast",
    titleKorean: "Iyagi - TTMIK Podcast",
    description: "TTMIK's podcast for learners covering culture, day-to-day life, and common experiences. Beginner and intermediate series available with transcripts.",
    descriptionKorean: "문화, 일상생활, 공통 경험을 다루는 학습자를 위한 TTMIK 팟캐스트. 대본이 있는 초급 및 중급 시리즈.",
    image: "/images/resources/iyagi.svg",
    link: "https://talktomeinkorean.com/iyagi/",
    level: "Beginner",
    category: "Podcast",
    tags: ["TTMIK", "culture", "daily life", "transcripts"],
    rating: 4.7,
    isFree: true,
    language: "Korean",
    features: [
      "Multiple levels",
      "Transcripts available",
      "Cultural topics",
      "Free episodes",
    ],
  },
  {
    id: "kids-donga-news",
    slug: "kids-donga-news",
    title: "Kid's Dong-a",
    titleKorean: "Kid's Dong-a",
    description: "A news site written for kids with simplified language, perfect for reading practice.",
    descriptionKorean: "간단한 언어로 작성된 어린이용 뉴스 사이트로 읽기 연습에 완벽합니다.",
    image: "/images/resources/kids-donga.svg",
    link: "https://kids.donga.com/",
    level: "Beginner",
    category: "Website",
    tags: ["news", "kids", "simplified", "reading practice"],
    rating: 4.3,
    isFree: true,
    language: "Korean",
    features: [
      "Simplified language",
      "News for kids",
      "Reading practice",
      "Free access",
    ],
  },
  // Stage 1B: Phonology
  {
    id: "youglish-korean-pronunciation",
    slug: "youglish-korean-pronunciation",
    title: "YouGlish - Korean",
    titleKorean: "YouGlish - Korean",
    description: "Look up words on YouTube to see native speakers actually using the word in context for pronunciation practice.",
    descriptionKorean: "YouTube에서 단어를 찾아 원어민이 실제로 문맥에서 단어를 사용하는 것을 보고 발음 연습을 할 수 있습니다.",
    image: "/images/resources/youglish.svg",
    link: "https://youglish.com/korean",
    level: "Beginner",
    category: "Tool",
    tags: ["pronunciation", "youtube", "context", "native speakers"],
    rating: 4.6,
    isFree: true,
    language: "Bilingual",
    features: [
      "Native pronunciation",
      "Context examples",
      "YouTube integration",
      "Free tool",
    ],
  },
  {
    id: "forvo-pronunciation",
    slug: "forvo-pronunciation",
    title: "Forvo - Korean Pronunciation",
    titleKorean: "Forvo - Korean Pronunciation",
    description: "Look up words to hear them pronounced by native speakers from different regions.",
    descriptionKorean: "다양한 지역의 원어민이 발음하는 단어를 찾아들을 수 있습니다.",
    image: "/images/resources/forvo.svg",
    link: "https://forvo.com/languages/ko/",
    level: "Beginner",
    category: "Tool",
    tags: ["pronunciation", "native speakers", "audio", "dictionary"],
    rating: 4.5,
    isFree: true,
    language: "Bilingual",
    features: [
      "Native pronunciations",
      "Multiple speakers",
      "Regional accents",
      "Free access",
    ],
  },
  {
    id: "korean-wikibooks-pronunciation",
    slug: "korean-wikibooks-pronunciation",
    title: "Korean Wikibooks - Pronunciation Rules",
    titleKorean: "Korean Wikibooks - Pronunciation Rules",
    description: "Long list of pronunciation rules complete with many examples for learning proper Korean pronunciation.",
    descriptionKorean: "적절한 한국어 발음을 배우기 위한 많은 예제가 포함된 긴 발음 규칙 목록.",
    image: "/images/resources/korean-wikibooks.svg",
    link: "https://en.wikibooks.org/wiki/Korean",
    level: "Beginner",
    category: "Website",
    tags: ["pronunciation", "rules", "examples", "reference"],
    rating: 4.3,
    isFree: true,
    language: "English",
    features: [
      "Pronunciation rules",
      "Examples",
      "Free resource",
      "Comprehensive",
    ],
  },
  {
    id: "fluent-forever-korean",
    slug: "fluent-forever-korean",
    title: "Fluent Forever - Korean Phonology",
    titleKorean: "Fluent Forever - Korean Phonology",
    description: "Video series about Korean phonology with clear explanations of tongue position and mouth shape, with examples from native speakers.",
    descriptionKorean: "원어민의 예제와 함께 혀 위치와 입 모양에 대한 명확한 설명이 있는 한국어 음성학에 대한 비디오 시리즈.",
    image: "/images/resources/fluent-forever.svg",
    link: "https://fluent-forever.com/korean/",
    level: "Beginner",
    category: "Video",
    tags: ["phonology", "pronunciation", "technique", "native examples"],
    rating: 4.5,
    isFree: true,
    language: "English",
    features: [
      "Phonology lessons",
      "Tongue position",
      "Mouth shape",
      "Native examples",
    ],
  },
  {
    id: "korean-abc-pronunciation",
    slug: "korean-abc-pronunciation",
    title: "Korean ABC",
    titleKorean: "Korean ABC",
    description: "Videos in Korean with Korean, English and Chinese subtitles introducing grammar, Hangeul, and proper pronunciation.",
    descriptionKorean: "문법, 한글, 적절한 발음을 소개하는 한국어, 영어, 중국어 자막이 있는 한국어 비디오.",
    image: "/images/resources/korean-abc.svg",
    link: "https://www.youtube.com/@KoreanABC",
    level: "Beginner",
    category: "Video",
    tags: ["hangeul", "pronunciation", "grammar", "multilingual"],
    rating: 4.4,
    isFree: true,
    language: "Korean",
    features: [
      "Multiple subtitles",
      "Hangeul lessons",
      "Pronunciation guide",
      "Grammar basics",
    ],
  },
  // Stage 1B: Writing System
  {
    id: "ryan-estrada-hangul",
    slug: "ryan-estrada-hangul",
    title: "Ryan Estrada's 15 Minute Guide to Hangeul",
    titleKorean: "Ryan Estrada's 15 Minute Guide to Hangeul",
    description: "Quick introduction to learning to read Korean with clever mnemonics for beginners.",
    descriptionKorean: "초보자를 위한 영리한 암기법으로 한국어 읽기를 배우는 빠른 소개.",
    image: "/images/resources/ryan-estrada.svg",
    link: "https://www.ryanestrada.com/learntoreadkoreanin15minutes/",
    level: "Beginner",
    category: "Website",
    tags: ["hangeul", "quick start", "mnemonics", "beginner"],
    rating: 4.7,
    isFree: true,
    language: "English",
    features: [
      "15-minute guide",
      "Clever mnemonics",
      "Quick learning",
      "Free resource",
    ],
  },
  {
    id: "georgetown-hangeul",
    slug: "georgetown-hangeul",
    title: "Georgetown - Korean Alphabet Origins",
    titleKorean: "Georgetown - Korean Alphabet Origins",
    description: "Website explaining the linguistic and philosophical origins of the Korean alphabet in a simple way.",
    descriptionKorean: "한국어 알파벳의 언어학적, 철학적 기원을 간단하게 설명하는 웹사이트.",
    image: "/images/resources/georgetown.svg",
    link: "http://www.korean.go.kr/",
    level: "Beginner",
    category: "Website",
    tags: ["hangeul", "history", "linguistics", "philosophy"],
    rating: 4.2,
    isFree: true,
    language: "English",
    features: [
      "Historical context",
      "Linguistic origins",
      "Educational",
      "Free access",
    ],
  },
  {
    id: "nativlang-hangeul",
    slug: "nativlang-hangeul",
    title: "NativLang - Korean Alphabet Video",
    titleKorean: "NativLang - Korean Alphabet Video",
    description: "YouTube video explaining the historic significance and interesting facts surrounding the invention of the Korean alphabet.",
    descriptionKorean: "한국 알파벳의 발명을 둘러싼 역사적 중요성과 흥미로운 사실을 설명하는 YouTube 비디오.",
    image: "/images/resources/nativlang.svg",
    link: "https://www.youtube.com/@NativLang",
    level: "Beginner",
    category: "Video",
    tags: ["hangeul", "history", "linguistics", "educational"],
    rating: 4.6,
    isFree: true,
    language: "English",
    features: [
      "Historical facts",
      "Linguistic insights",
      "Educational video",
      "Free content",
    ],
  },
  {
    id: "professor-yoon-hangul",
    slug: "professor-yoon-hangul",
    title: "Professor Yoon - Hangeul Series",
    titleKorean: "Professor Yoon - Hangeul Series",
    description: "Native speaker series on Hangeul with great examples of native pronunciation.",
    descriptionKorean: "원어민 발음의 훌륭한 예제가 있는 한글에 대한 원어민 시리즈.",
    image: "/images/resources/professor-yoon.svg",
    link: "https://www.youtube.com/@ProfessorYoon",
    level: "Beginner",
    category: "Video",
    tags: ["hangeul", "native speaker", "pronunciation", "series"],
    rating: 4.5,
    isFree: true,
    language: "Korean",
    features: [
      "Native pronunciation",
      "Hangeul focus",
      "Video series",
      "Free lessons",
    ],
  },
  {
    id: "go-billy-hangul",
    slug: "go-billy-hangul",
    title: "Go! Billy - Hangeul Series",
    titleKorean: "Go! Billy - Hangeul Series",
    description: "Series on Hangeul that discusses sound change rules and writing system basics.",
    descriptionKorean: "소리 변화 규칙과 쓰기 시스템 기초를 다루는 한글 시리즈.",
    image: "/images/resources/go-billy.svg",
    link: "https://www.gobillykorean.com/",
    level: "Beginner",
    category: "Video",
    tags: ["hangeul", "sound changes", "writing", "rules"],
    rating: 4.6,
    isFree: true,
    language: "English",
    features: [
      "Sound change rules",
      "Writing system",
      "Video lessons",
      "Clear explanations",
    ],
  },
  {
    id: "korean-handwriting",
    slug: "korean-handwriting",
    title: "Korean Handwriting Channel",
    titleKorean: "Korean Handwriting Channel",
    description: "Video on basic Korean penmanship showing what typical adult handwritten script looks like and how it is written.",
    descriptionKorean: "일반적인 성인 손글씨가 어떻게 생겼고 어떻게 쓰이는지 보여주는 기본 한국어 서예에 대한 비디오.",
    image: "/images/resources/korean-handwriting.svg",
    link: "https://www.youtube.com/@koreanhandwriting",
    level: "Beginner",
    category: "Video",
    tags: ["handwriting", "penmanship", "writing", "practical"],
    rating: 4.3,
    isFree: true,
    language: "Korean",
    features: [
      "Handwriting guide",
      "Practical examples",
      "Adult script",
      "Free lessons",
    ],
  },
  {
    id: "pinkfong-alphabet",
    slug: "pinkfong-alphabet",
    title: "Pink Fong - Korean Alphabet Song",
    titleKorean: "Pink Fong - Korean Alphabet Song",
    description: "Cute cartoon video of a Korean alphabet song for children introducing each basic consonant with vocabulary.",
    descriptionKorean: "각 기본 자음과 어휘를 소개하는 어린이를 위한 한국어 알파벳 노래의 귀여운 만화 비디오.",
    image: "/images/resources/pink-fong.svg",
    link: "https://www.youtube.com/@pinkfong",
    level: "Beginner",
    category: "Video",
    tags: ["song", "alphabet", "kids", "fun"],
    rating: 4.4,
    isFree: true,
    language: "Korean",
    features: [
      "Alphabet song",
      "Kids content",
      "Cute animation",
      "Educational",
    ],
  },
  {
    id: "andrew-kim-vowels",
    slug: "andrew-kim-vowels",
    title: "Andrew Kim - Korean Vowel Song",
    titleKorean: "Andrew Kim - Korean Vowel Song",
    description: "Funky song introducing all Korean vowels and vocabulary items that use them.",
    descriptionKorean: "모든 한국어 모음과 그것을 사용하는 어휘 항목을 소개하는 펑키한 노래.",
    image: "/images/resources/andrew-kim.svg",
    link: "https://www.youtube.com/@AndrewKim",
    level: "Beginner",
    category: "Video",
    tags: ["vowels", "song", "fun", "memorable"],
    rating: 4.3,
    isFree: true,
    language: "Korean",
    features: ["Vowel song", "Vocabulary", "Catchy tune", "Educational"],
  },
  // Stage 1C: Grammar Resources
  {
    id: "talk-to-me-in-korean-grammar",
    slug: "talk-to-me-in-korean-grammar",
    title: "Talk To Me In Korean",
    titleKorean: "Talk To Me In Korean",
    description: "Free curriculum covering a broad range of grammar points, explained succinctly with example sentences.",
    descriptionKorean: "예문과 함께 간결하게 설명된 광범위한 문법 포인트를 다루는 무료 커리큘럼.",
    image: "/images/resources/ttmik.svg",
    link: "https://talktomeinkorean.com/",
    level: "Beginner",
    category: "Website",
    tags: ["grammar", "free", "comprehensive", "examples"],
    rating: 4.8,
    isFree: true,
    language: "English",
    features: [
      "Free lessons",
      "Grammar explanations",
      "Example sentences",
      "Audio content",
    ],
  },
  {
    id: "how-to-study-korean-grammar",
    slug: "how-to-study-korean-grammar",
    title: "How To Study Korean",
    titleKorean: "How To Study Korean",
    description: "Free curriculum with over 158 lessons. Extremely in depth, good reference for specific grammar terms.",
    descriptionKorean: "158개 이상의 레슨이 있는 무료 커리큘럼. 매우 상세하며 특정 문법 용어에 대한 좋은 참고 자료.",
    image: "/images/resources/how-to-study-korean.svg",
    link: "https://www.howtostudykorean.com/",
    level: "Intermediate",
    category: "Website",
    tags: ["grammar", "comprehensive", "detailed", "reference"],
    rating: 4.7,
    isFree: true,
    language: "English",
    features: [
      "158+ lessons",
      "In-depth explanations",
      "Grammar reference",
      "Free access",
    ],
  },
  {
    id: "ultimate-korean-grammar",
    slug: "ultimate-korean-grammar",
    title: "UltimateKOREAN",
    titleKorean: "UltimateKOREAN",
    description: "Reference grammar for lookups alongside immersion, with academic lessons and user-submitted example sentences.",
    descriptionKorean: "몰입과 함께 참고용 문법, 학술 레슨 및 사용자 제출 예문.",
    image: "/images/resources/ultimate-korean.svg",
    link: "https://ultimatekorean.com/",
    level: "Intermediate",
    category: "Website",
    tags: ["grammar", "reference", "academic", "examples"],
    rating: 4.4,
    isFree: true,
    language: "English",
    features: [
      "Reference grammar",
      "Academic content",
      "User examples",
      "Active development",
    ],
  },
  {
    id: "korean-wiki-project-grammar",
    slug: "korean-wiki-project-grammar",
    title: "Korean Wiki Project",
    titleKorean: "Korean Wiki Project",
    description: "Growing collection of Korean grammar and other language content, community-driven resource.",
    descriptionKorean: "한국어 문법 및 기타 언어 콘텐츠의 성장하는 컬렉션, 커뮤니티 주도 리소스.",
    image: "/images/resources/korean-wiki-project.svg",
    link: "https://www.koreanwikiproject.com/",
    level: "Intermediate",
    category: "Website",
    tags: ["grammar", "wiki", "community", "growing"],
    rating: 4.3,
    isFree: true,
    language: "English",
    features: [
      "Community content",
      "Grammar collection",
      "Wiki format",
      "Free resource",
    ],
  },
  {
    id: "korean-grammar-dictionary",
    slug: "korean-grammar-dictionary",
    title: "Korean Grammar Dictionary",
    titleKorean: "Korean Grammar Dictionary",
    description: "Comprehensive dictionary of Korean grammar points for reference and study.",
    descriptionKorean: "참고 및 학습을 위한 한국어 문법 포인트의 포괄적인 사전.",
    image: "/images/resources/korean-grammar-dictionary.svg",
    link: "https://krdict.korean.go.kr/",
    level: "Intermediate",
    category: "Tool",
    tags: ["grammar", "dictionary", "reference", "comprehensive"],
    rating: 4.5,
    isFree: true,
    language: "Bilingual",
    features: [
      "Grammar dictionary",
      "Comprehensive",
      "Reference tool",
      "Free access",
    ],
  },
  {
    id: "pusan-grammar-checker",
    slug: "pusan-grammar-checker",
    title: "Pusan National University Grammar Checker",
    titleKorean: "Pusan National University Grammar Checker",
    description: "Webpage that corrects grammar and spelling errors. Made for native speakers but useful for learners.",
    descriptionKorean: "문법 및 철자 오류를 수정하는 웹페이지. 원어민용이지만 학습자에게 유용합니다.",
    image: "/images/resources/pusan-grammar.svg",
    link: "https://speller.cs.pusan.ac.kr/",
    level: "Advanced",
    category: "Tool",
    tags: ["grammar", "spelling", "checker", "correction"],
    rating: 4.2,
    isFree: true,
    language: "Korean",
    features: [
      "Grammar checking",
      "Spelling correction",
      "Free tool",
      "University made",
    ],
  },
  {
    id: "korean-verb-conjugator-app",
    slug: "korean-verb-conjugator-app",
    title: "Korean Verb Conjugator",
    titleKorean: "Korean Verb Conjugator",
    description: "Input a verb and this page will conjugate to almost every imaginable form. Essential tool for learners.",
    descriptionKorean: "동사를 입력하면 거의 모든 상상 가능한 형태로 활용합니다. 학습자를 위한 필수 도구.",
    image: "/images/resources/verb-conjugator.svg",
    link: "https://www.koreanverb.app/",
    level: "Intermediate",
    category: "Tool",
    tags: ["verbs", "conjugation", "tool", "comprehensive"],
    rating: 4.7,
    isFree: true,
    language: "Bilingual",
    features: ["Verb conjugation", "All forms", "Easy to use", "Free tool"],
  },
  {
    id: "verbix-korean",
    slug: "verbix-korean",
    title: "Verbix - Korean Conjugator",
    titleKorean: "Verbix - Korean Conjugator",
    description: "Another comprehensive verb conjugation tool for Korean language learners.",
    descriptionKorean: "한국어 학습자를 위한 또 다른 포괄적인 동사 활용 도구.",
    image: "/images/resources/verbix.svg",
    link: "https://www.verbix.com/languages/korean.html",
    level: "Intermediate",
    category: "Tool",
    tags: ["verbs", "conjugation", "tool", "reference"],
    rating: 4.4,
    isFree: true,
    language: "Bilingual",
    features: [
      "Verb conjugation",
      "Multiple forms",
      "Quick reference",
      "Free tool",
    ],
  },
  {
    id: "sip-language-videos",
    slug: "sip-language-videos",
    title: "SIP Language",
    titleKorean: "SIP Language",
    description: "Website teaching grammar points and vocabulary through watching videos using acquisition and comprehensible input with SRS.",
    descriptionKorean: "습득 및 이해 가능한 입력과 SRS를 사용하여 비디오를 보면서 문법 포인트와 어휘를 가르치는 웹사이트.",
    image: "/images/resources/sip-language.svg",
    link: "https://siplanguage.com/",
    level: "Intermediate",
    category: "Website",
    tags: ["video", "grammar", "vocabulary", "SRS"],
    rating: 4.3,
    isFree: false,
    language: "Bilingual",
    features: [
      "Video learning",
      "SRS system",
      "Grammar lessons",
      "Vocabulary building",
    ],
  },
  {
    id: "mirinae-analyzer",
    slug: "mirinae-analyzer",
    title: "Mirinae - Korean Sentence Analyzer",
    titleKorean: "Mirinae - Korean Sentence Analyzer",
    description: "Korean sentence analyzer that dissects the grammar of any sentence and defines each word.",
    descriptionKorean: "문장의 문법을 분석하고 각 단어를 정의하는 한국어 문장 분석기.",
    image: "/images/resources/mirinae.svg",
    link: "https://mirinae.io/",
    level: "Intermediate",
    category: "Tool",
    tags: ["grammar", "analyzer", "parser", "definitions"],
    rating: 4.6,
    isFree: true,
    language: "Bilingual",
    features: [
      "Sentence analysis",
      "Grammar breakdown",
      "Word definitions",
      "Free tool",
    ],
  },
  {
    id: "gobilly-korean-grammar",
    slug: "gobilly-korean-grammar",
    title: "GoBillyKorean",
    titleKorean: "GoBillyKorean",
    description: "118+ episode series on grammar, beginner series up to CEFR A1, live lectures, and various videos on Korean and Korea.",
    descriptionKorean: "문법에 대한 118개 이상의 에피소드 시리즈, CEFR A1까지의 초급 시리즈, 라이브 강의 및 한국어와 한국에 대한 다양한 비디오.",
    image: "/images/resources/go-billy.svg",
    link: "https://www.gobillykorean.com/",
    level: "Beginner",
    category: "Video",
    tags: ["grammar", "series", "comprehensive", "live"],
    rating: 4.6,
    isFree: true,
    language: "English",
    features: [
      "118+ episodes",
      "Grammar series",
      "Live lectures",
      "Beginner friendly",
    ],
  },
  {
    id: "cyber-university-korea-course",
    slug: "cyber-university-korea-course",
    title: "Cyber University of Korea",
    titleKorean: "Cyber University of Korea",
    description: "100-episode beginner series in full Korean with high-quality Korean and English subtitles, covering phonetics through TOPIK level 3.",
    descriptionKorean: "음성학부터 TOPIK 3급까지 다루는 고품질 한국어 및 영어 자막이 있는 100개 에피소드 초급 시리즈.",
    image: "/images/resources/cyber-university.svg",
    link: "https://www.youtube.com/c/CyberUniversityKorea",
    level: "Intermediate",
    category: "Course",
    tags: ["university", "100 episodes", "TOPIK", "subtitles"],
    rating: 4.7,
    isFree: true,
    language: "Korean",
    features: [
      "100 episodes",
      "University quality",
      "TOPIK prep",
      "Dual subtitles",
    ],
  },
  // Frequency Lists & Vocabulary
  {
    id: "wiktionary-frequency-list",
    slug: "wiktionary-frequency-list",
    title: "Wiktionary - Korean Frequency List",
    titleKorean: "Wiktionary - Korean Frequency List",
    description: "List of 5800 Korean words organized by frequency of use.",
    descriptionKorean: "사용 빈도별로 정리된 5800개의 한국어 단어 목록.",
    image: "/images/resources/wiktionary-frequency.svg",
    link: "https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Korean",
    level: "Intermediate",
    category: "Tool",
    tags: ["frequency", "vocabulary", "list", "reference"],
    rating: 4.4,
    isFree: true,
    language: "Bilingual",
    features: [
      "5800 words",
      "Frequency order",
      "Free resource",
      "Reference tool",
    ],
  },
  {
    id: "naver-topik-vocab",
    slug: "naver-topik-vocab",
    title: "Naver TOPIK Vocabulary Lists",
    titleKorean: "Naver TOPIK Vocabulary Lists",
    description: "Official vocabulary lists for TOPIK exam preparation at beginner and intermediate levels.",
    descriptionKorean: "초급 및 중급 수준의 TOPIK 시험 준비를 위한 공식 어휘 목록.",
    image: "/images/resources/naver-topik.svg",
    link: "https://dict.naver.com/",
    level: "Intermediate",
    category: "Tool",
    tags: ["TOPIK", "vocabulary", "exam prep", "official"],
    rating: 4.6,
    isFree: true,
    language: "Bilingual",
    features: [
      "TOPIK vocabulary",
      "Multiple levels",
      "Official lists",
      "Exam preparation",
    ],
  },
  {
    id: "refold-ko1k-anki",
    slug: "refold-ko1k-anki",
    title: "Official Refold KO1K 1000 Word Deck",
    titleKorean: "Official Refold KO1K 1000 Word Deck",
    description: "Built from kdrama subtitles, designed to jumpstart comprehension of real native Korean media.",
    descriptionKorean: "K드라마 자막에서 구축되어 실제 원어민 한국어 미디어의 이해를 촉진하도록 설계되었습니다.",
    image: "/images/resources/refold-ko1k.svg",
    link: "https://refold.la/ko1k",
    level: "Intermediate",
    category: "Tool",
    tags: ["anki", "1000 words", "kdrama", "frequency"],
    rating: 4.8,
    isFree: true,
    language: "Bilingual",
    features: [
      "1000 words",
      "Kdrama based",
      "Anki deck",
      "Comprehension focused",
    ],
  },
  {
    id: "ttmik-500-words-anki",
    slug: "ttmik-500-words-anki",
    title: "TTMIK First 500 Words Anki Deck",
    titleKorean: "TTMIK First 500 Words Anki Deck",
    description: "Anki deck made from the popular beginner vocabulary book from Talk To Me In Korean.",
    descriptionKorean: "Talk To Me In Korean의 인기 초급 어휘 책으로 만든 Anki 덱.",
    image: "/images/resources/ttmik-500.svg",
    link: "https://ankiweb.net/",
    level: "Beginner",
    category: "Tool",
    tags: ["anki", "TTMIK", "500 words", "beginner"],
    rating: 4.5,
    isFree: true,
    language: "Bilingual",
    features: ["500 words", "TTMIK based", "Anki format", "Beginner friendly"],
  },
  {
    id: "10k-frequency-deck",
    slug: "10k-frequency-deck",
    title: "10k+ Korean Frequency Deck",
    titleKorean: "10k+ Korean Frequency Deck",
    description: "Large Anki deck with 10,000+ words sorted by frequency from the 2005 Korean census.",
    descriptionKorean: "2005년 한국어 인구 조사에서 빈도별로 정렬된 10,000개 이상의 단어가 있는 대형 Anki 덱.",
    image: "/images/resources/10k-frequency.svg",
    link: "https://ankiweb.net/",
    level: "Advanced",
    category: "Tool",
    tags: ["anki", "10000 words", "frequency", "comprehensive"],
    rating: 4.6,
    isFree: true,
    language: "Bilingual",
    features: [
      "10,000+ words",
      "Frequency sorted",
      "Census data",
      "Comprehensive",
    ],
  },
  {
    id: "viki-learn-mode",
    slug: "viki-learn-mode",
    title: "Viki - Korean Dramas with Subtitles",
    titleKorean: "Viki - Korean Dramas with Subtitles",
    description: "Over 800 Korean series with community-added subtitles. About 280 series have Korean subtitles available.",
    descriptionKorean: "커뮤니티가 추가한 자막이 있는 800개 이상의 한국 시리즈. 약 280개 시리즈에 한국어 자막이 있습니다.",
    image: "/images/resources/viki.svg",
    link: "https://www.viki.com/",
    level: "Intermediate",
    category: "Video",
    tags: ["dramas", "subtitles", "streaming", "community"],
    rating: 4.7,
    isFree: false,
    language: "Korean",
    features: [
      "800+ series",
      "Community subtitles",
      "Learn mode",
      "Multiple languages",
    ],
  },
  {
    id: "naver-comics-webtoons",
    slug: "naver-comics-webtoons",
    title: "Naver Comics",
    titleKorean: "Naver Comics",
    description: "Korea's largest webtoon platform with thousands of titles for reading practice.",
    descriptionKorean: "읽기 연습을 위한 수천 개의 타이틀이 있는 한국 최대의 웹툰 플랫폼.",
    image: "/images/resources/placeholder.svg",
    link: "https://comic.naver.com/",
    level: "Intermediate",
    category: "Website",
    tags: ["webtoon", "comics", "reading", "native content"],
    rating: 4.8,
    isFree: true,
    language: "Korean",
    features: [
      "Thousands of webtoons",
      "Various genres",
      "Free access",
      "Updated regularly",
    ],
  },
  {
    id: "kosnet-streaming",
    slug: "kosnet-streaming",
    title: "KOSNET",
    titleKorean: "KOSNET",
    description: "Korean streaming service with dramas, variety shows, and Korean content.",
    descriptionKorean: "드라마, 예능 프로그램, 한국 콘텐츠가 있는 한국 스트리밍 서비스.",
    image: "/images/resources/kosnet.svg",
    link: "https://www.kosnet.com/",
    level: "Intermediate",
    category: "Video",
    tags: ["streaming", "dramas", "variety", "Korean content"],
    rating: 4.4,
    isFree: false,
    language: "Korean",
    features: [
      "Korean dramas",
      "Variety shows",
      "Streaming service",
      "Korean content",
    ],
  },
  // Dictionary Resources
  {
    id: "naver-dict-korean",
    slug: "naver-dict-korean",
    title: "Naver Dictionary",
    titleKorean: "Naver Dictionary",
    description: "Comprehensive Korean-English dictionary with pronunciation, examples, and frequency information.",
    descriptionKorean: "발음, 예문, 빈도 정보가 있는 포괄적인 한영 사전.",
    image: "/images/resources/naver-dict.svg",
    link: "https://dict.naver.com/",
    level: "Beginner",
    category: "Tool",
    tags: ["dictionary", "pronunciation", "examples", "frequency"],
    rating: 4.7,
    isFree: true,
    language: "Bilingual",
    features: ["Comprehensive", "Pronunciation", "Examples", "Frequency stars"],
  },
  {
    id: "korean-hanja-dictionary",
    slug: "korean-hanja-dictionary",
    title: "KoreanHanja.app",
    titleKorean: "KoreanHanja.app",
    description: "Dictionary for hanja (Chinese characters) used in Korean, showing meaning and related words.",
    descriptionKorean: "한국어에 사용되는 한자 사전으로 의미와 관련 단어를 보여줍니다.",
    image: "/images/resources/korean-hanja.svg",
    link: "https://koreanhanja.app/",
    level: "Advanced",
    category: "Tool",
    tags: ["hanja", "chinese characters", "dictionary", "etymology"],
    rating: 4.5,
    isFree: true,
    language: "Bilingual",
    features: ["Hanja lookup", "Word relationships", "Etymology", "Free tool"],
  },
  {
    id: "voice-of-america-korean-news",
    slug: "voice-of-america-korean-news",
    title: "Voice of America - Korean",
    titleKorean: "Voice of America - Korean",
    description: "Korean language news about Korea, the United States and the World for listening and reading practice.",
    descriptionKorean: "한국, 미국, 세계에 대한 한국어 뉴스로 듣기와 읽기 연습에 좋습니다.",
    image: "/images/resources/voa.svg",
    link: "https://www.voakorea.com/",
    level: "Advanced",
    category: "Website",
    tags: ["news", "listening", "reading", "current events"],
    rating: 4.5,
    isFree: true,
    language: "Korean",
    features: [
      "Daily news",
      "Audio content",
      "Reading practice",
      "Current events",
    ],
  },
  {
    id: "dliflc-korean",
    slug: "dliflc-korean",
    title: "DLIFLC Korean Courses",
    titleKorean: "DLIFLC Korean Courses",
    description: "Defense Language Institute Foreign Language Center Korean language courses and materials.",
    descriptionKorean: "국방 언어 연구소 외국어 센터 한국어 과정 및 자료.",
    image: "/images/resources/dliflc.svg",
    link: "https://www.dliflc.edu/",
    level: "Intermediate",
    category: "Course",
    tags: ["military", "comprehensive", "structured", "official"],
    rating: 4.6,
    isFree: true,
    language: "English",
    features: [
      "Military standard",
      "Comprehensive",
      "Structured learning",
      "Free resources",
    ],
  },
  {
    id: "duolingo-korean",
    slug: "duolingo-korean",
    title: "Duolingo - Korean",
    titleKorean: "Duolingo - Korean",
    description: "Popular language learning app with gamified Korean lessons for beginners.",
    descriptionKorean: "초보자를 위한 게임화된 한국어 레슨이 있는 인기 언어 학습 앱.",
    image: "/images/resources/duolingo.svg",
    link: "https://www.duolingo.com/course/ko/en/Learn-Korean",
    level: "Beginner",
    category: "App",
    tags: ["app", "gamified", "beginner", "popular"],
    rating: 4.2,
    isFree: true,
    language: "English",
    features: [
      "Gamified learning",
      "Mobile app",
      "Beginner friendly",
      "Free tier",
    ],
  },
  {
    id: "sogang-korean",
    slug: "sogang-korean",
    title: "Sogang Korean Program",
    titleKorean: "Sogang Korean Program",
    description: "University-level Korean language program with comprehensive materials and structured curriculum.",
    descriptionKorean: "포괄적인 자료와 구조화된 커리큘럼이 있는 대학 수준의 한국어 프로그램.",
    image: "/images/resources/sogang.svg",
    link: "https://klec.sogang.ac.kr/",
    level: "Intermediate",
    category: "Course",
    tags: ["university", "structured", "comprehensive", "academic"],
    rating: 4.7,
    isFree: false,
    language: "Bilingual",
    features: [
      "University program",
      "Structured curriculum",
      "Comprehensive",
      "Academic quality",
    ],
  },
  {
    id: "spongemind-podcast",
    slug: "spongemind-podcast",
    title: "SpongeMind Podcast",
    titleKorean: "SpongeMind Podcast",
    description: "Korean podcast covering various topics for intermediate to advanced learners.",
    descriptionKorean: "중급부터 고급 학습자를 위한 다양한 주제를 다루는 한국어 팟캐스트.",
    image: "/images/resources/spongemind.svg",
    link: "https://www.youtube.com/@SpongeMind",
    level: "Advanced",
    category: "Podcast",
    tags: ["podcast", "various topics", "advanced", "native"],
    rating: 4.5,
    isFree: true,
    language: "Korean",
    features: [
      "Podcast format",
      "Various topics",
      "Native content",
      "Regular episodes",
    ],
  },
];

async function addRefoldResources() {
  try {
    console.log("Connecting to MongoDB...");
    await connectDB();
    console.log("Connected to MongoDB");

    console.log(`\nAdding ${refoldResources.length} Refold resources...`);

    let addedCount = 0;
    let skippedCount = 0;

    for (const resource of refoldResources) {
      try {
        // Check if resource already exists
        const existing = await Resource.findOne({ id: resource.id });
        if (existing) {
          console.log(`⏭️  Skipped: ${resource.title} (already exists)`);
          skippedCount++;
          continue;
        }

        await Resource.create(resource);
        console.log(`✅ Added: ${resource.title}`);
        addedCount++;
      } catch (error: any) {
        if (error?.code === 11000) {
          console.log(`⏭️  Skipped: ${resource.title} (duplicate)`);
          skippedCount++;
        } else {
          console.error(`❌ Error adding ${resource.title}:`, error?.message ?? String(error));
        }
      }
    }

    console.log(`\n✅ Successfully added ${addedCount} new resources`);
    console.log(`⏭️  Skipped ${skippedCount} existing resources`);

    const totalCount = await Resource.countDocuments();
    console.log(`📊 Total resources in database: ${totalCount}`);
  } catch (error: any) {
    console.error("Error adding Refold resources:", error?.message ?? String(error));
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log("\n✅ Database connection closed");
  }
}

addRefoldResources();